name: Selenium Test

on:
  push:
    branches: 
      - 'image*'

env:
    REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
    REGISTRY_USER: ${{ vars.REGISTRY_USER }}
    REGISTRY: ${{ vars.REGISTRY }}

jobs:
  # build:
  #   runs-on: ubuntu-latest #use the latest ubuntu container image 
  #   steps:
  #     - name: Checkout the code
  #       uses: actions/checkout@v3

  #     - name: Check Vars
  #       run: |
  #         echo $REGISTRY_USER

  #     - name: Build the image
  #       run: |
  #         make build
        
  #     - name: Push beta version
  #       run: |
  #         docker login $REGISTRY -u $REGISTRY_USER -p $REGISTRY_PASSWORD
  #         make push-beta
      
  
  test:
    runs-on: ubuntu-latest #use the latest ubuntu container image
    # needs: build
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
        
       # Need to fetch reqs if needed

      - name: Install Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Installing necessary python packages
        run: pip install selenium webdriver_manager jupyterlab
          
      - name: Pull beta-version
        run: |
          make pull-beta

      - name: Run JupyterLab inside container
        run: |
          make run &
          sleep 3

      # - name: Show debug info
      #   run: |
      #     IMAGE_TAG=$( make show-tag )
      #     echo "For debugging purposes, here is the image tag:"
      #     echo "  $IMAGE_TAG"

      # - name: Comparing checksum value
      #   run: |
      #     PERMISSIONS_CHECKSUM=$( make checksum )
      #     echo $PERMISSIONS_CHECKSUM
      #     QUICK_TRIM=${PERMISSIONS_CHECKSUM::64}
      #     #CHECKSUM=$( cat base/checksum.txt )
      #     if [[ "$QUICK_TRIM == $CHECKSUM" ]]; then
      #           echo "SUCCESS" 
      #     else 
      #           echo "FAILURE"
      #           echo "Here is the image checksum:"
      #           echo "  $QUICK_TRIM"
      #           echo "Here is the correct checksum:"
      #           echo "  $CHECKSUM"
      #     fi

      - name: Run Selenium tests
        run: |
          container_id=$(docker ps -q | head -n 1)
          echo $container_id
          url=$(docker exec $container_id jupyter lab list 2>&1 | grep -o 'http://[^[:space:]]*')
          echo $url
  
  # approval:
  #   needs: test
  #   environment:
  #     name: approval
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: manual approve
  #     run: |
  #         echo "Publication approved"

  # publish:
  #   runs-on: ubuntu-latest #use the latest ubuntu container image
  #   needs: approval
  #   steps:
  #     - name: Checkout the code
  #       uses: actions/checkout@v3

  #     - name: Push to public version
  #       run: |
  #         docker login $REGISTRY -u $REGISTRY_USER -p $REGISTRY_PASSWORD
  #         make publish